### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by justinpenner** [justinpenner/type-design-resources#10]
- [ ] Add a libre license to the repo
- [ ] Rewrite [Software](https://typedesignresources.com/#software) item descriptions to sound more impartial (#6).
- [ ] Update [Software](https://typedesignresources.com/#software) category description and item descriptions to better explain the differences/pros/cons of each (but keep them very brief).
- [ ] Add descriptions (one line/sentence) to the [Web specimen tools](https://typedesignresources.com/#web-specimen-tools) items.
- [ ] Find more website platforms to add to [Website platforms](https://typedesignresources.com/#website-platforms). Any platform that might be particularly good for a foundry website, either for a developer working on it, or for someone starting a foundry and DIYing their website.
- [ ] Expand [Community/Groups](https://typedesignresources.com/#groups) to include more regional in-person groups, like the ones mentioned [here on TypeDrawers](https://typedrawers.com/discussion/4696/minneapolis-st-paul-type-design-interest-group)
- [ ] Add a *Python scripting for FontLab* section
- [ ] Add a *Python scripting for FontForge* section

**Anyone is welcome to contribute by working on these items, or suggesting more items to add to this list. Submit a PR or open an issue for anything you want to add/update.**
